# Generated by Django 5.0.3 on 2024-04-24 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(blank=True, max_length=16, null=True, verbose_name='Coupon')),
                ('discount', models.PositiveSmallIntegerField(default=1, verbose_name='Discount')),
                ('drop_chance', models.PositiveSmallIntegerField(default=1, verbose_name='Chance to drop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['discount'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(auto_now_add=True, verbose_name='Coupon start date')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Coupon valid to')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupons', verbose_name='Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'user coupon',
                'verbose_name_plural': "Users' coupons",
            },
        ),
    ]
