# Generated by Django 5.0.3 on 2024-03-19 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_full_name_remove_usershippinginfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company name')),
                ('company_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company address')),
                ('company_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company city')),
                ('company_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company country')),
                ('company_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Company phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
    ]
