# Generated by Django 5.0.3 on 2024-04-26 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0002_customertransaction_status_storetransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransaction',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_transactions', to='accounts.store'),
            preserve_default=False,
        ),
    ]
