# Generated by Django 5.0.3 on 2024-05-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_storetransaction_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storetransaction',
            name='product_variation',
        ),
    ]
