# Generated by Django 5.0.3 on 2024-04-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='product_variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productvariation', verbose_name='Product Variation'),
            preserve_default=False,
        ),
    ]
