# Generated by Django 5.0.3 on 2024-04-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcharacteristics',
            name='characteristics_category',
        ),
        migrations.RemoveField(
            model_name='productcharacteristics',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='description_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.DeleteModel(
            name='ProductCharacteristicsCategory',
        ),
        migrations.DeleteModel(
            name='ProductCharacteristics',
        ),
        migrations.DeleteModel(
            name='ProductDescriptionCategory',
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
