# Generated by Django 5.0.3 on 2024-04-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productcharacteristics_characteristics_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability_status',
            field=models.IntegerField(choices=[(1, 'in stock'), (2, 'awaiting arrival'), (3, 'low in stock'), (4, 'out of stock')], default=4),
        ),
    ]
